### ISSUE TITLE
Specifying Functional Software Requirements

### ISSUE THREAD

**Issue by ozercevikaslan** [ozercevikaslan/traffic-scenario-simulation#1]
[SoftwareRequirementsSpecification.docx](https://github.com/ozercevikaslan/traffic-scenario-simulation/files/848428/SoftwareRequirementsSpecification.docx)

The blank part for Functional Requirements in the document above will be handled by basarrcan and dogancan35.

Priority : 2

Difficulty : 2

Modifier : 0

**Comment by ozercevikaslan** [comment]
[SoftwareRequirementsSpecification-Functional Requirements.docx](https://github.com/ozercevikaslan/traffic-scenario-simulation/files/857581/SoftwareRequirementsSpecification-Functional.Requirements.docx)

Document on the top was prepared by Doğancan and Başarcan.

**Comment by koguz** [comment]
I'm sorry, I will not read a DOCX file. 

The tasks are missing. Who did what in this document? Where are the tasks, their points etc.?

**Comment by basarrcan** [comment]
[SoftwareRequirementsSpecification-Functional.Requirements.pdf](https://github.com/ozercevikaslan/traffic-scenario-simulation/files/891523/SoftwareRequirementsSpecification-Functional.Requirements.pdf)
