### ISSUE TITLE
Specifying Non-Functional Requirements

### ISSUE THREAD

**Issue by ozercevikaslan** [ozercevikaslan/traffic-scenario-simulation#2]
[SoftwareRequirementsSpecification.docx](https://github.com/ozercevikaslan/traffic-scenario-simulation/files/848497/SoftwareRequirementsSpecification.docx)

The blank part for Non-Functional Requirements in the document above will be handled by semihpehlivan and burkay35.

Priority : 2

Difficulty : 2

Modifier : 0

**Comment by burkay35** [comment]
[non-func..txt](https://github.com/ozercevikaslan/traffic-scenario-simulation/files/848689/non-func.txt)
